auctions/urls.py
from django.urls import path

from . import views

app_name = "commerce"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new", views.new, name="new"),
    path("categories", views.categories, name="categories"),
    path("categories/<str:category>", views.category, name="category"),
    path("listing/<int:id>", views.listing, name="listing"),
    path("watchlist/<int:listing_id>", views.toggle_watchlist, name="toggle_watchlist"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("comment/<int:listing_id>", views.add_comment, name="add_comment"),
    path("close_auction/<int:listing_id>", views.close_listing, name="close_listing")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from tkinter import CASCADE
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass

class Category(models.Model):
    name = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"

class Listing(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=300)
    starting_bid = models.PositiveIntegerField()
    current_bid = models.PositiveBigIntegerField()
    image = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="listings", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listings")
    created_at = models.DateTimeField(auto_now_add=True)
    closed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title}: {self.description}"


class Bid(models.Model):
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")
    amount = models.PositiveIntegerField()
    
class Watchlist(models.Model):
    listing=models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="watchlist")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watchlist")

class Comment(models.Model):
    comment = models.CharField(max_length=150)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
    created_at = models.DateTimeField(auto_now_add=True)

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Category, Listing, User, Bid, Watchlist, Comment


def index(request):
    return render(request, "auctions/index.html", {
        'listings': Listing.objects.all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("commerce:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("commerce:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("commerce:index"))
    else:
        return render(request, "auctions/register.html")





@login_required(login_url='login') 
def new(request):
    if request.method == "POST":
        form = NewListingForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            starting_bid = form.cleaned_data['starting_bid']
            image = form.cleaned_data['image_url']
            if 'category' not in request.POST:
                category = Category.objects.get(name='None')
            else:
                category = Category.objects.get(name=request.POST['category'])
            user = request.user
            new_listing = Listing(title=title,
                                    description=description,
                                    starting_bid=starting_bid,
                                    current_bid=starting_bid,
                                    image=image,
                                    category=category,
                                    user=user)
            new_listing.save()

            return HttpResponseRedirect(reverse("commerce:index"))
        else:
            return render(request, "auctions/new.html", {
                "message": "Invalid Submission",
                "form": NewListingForm(),
                "categories": Category.objects.all()
            })

    return render(request, "auctions/new.html", {
        "form": NewListingForm(),
        "categories": Category.objects.all()
    })


class NewListingForm(forms.Form):
    title = forms.CharField(label = 'Title', widget=forms.TextInput(attrs={'class': "form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': "form-control"}))
    starting_bid = forms.IntegerField(min_value=1, widget=forms.TextInput(attrs={'class': "form-control"}))
    image_url = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': "form-control"}))
    
    
def categories(request):
    return render(request, "auctions/categories.html", {
        "categories": Category.objects.all()
    })

def category(request, category):

    return render(request, "auctions/category.html", {
        "category": Category.objects.get(name=category),
        "listings": Category.objects.get(name=category).listings.all()
    })


def listing(request, id):
    listing = Listing.objects.get(pk=id)
    winner = False
    if listing.closed:
        winning_user = listing.bids.latest('amount').user
        if request.user == winning_user:
            winner = True


        return render(request, "auctions/closed_listing.html", {
            "listing": listing,
            "winner": winner,
            "winning_user": winning_user
        })



    listing_user = listing.user
    bids_no = listing.bids.count()
    comment_form = NewCommentForm()
    category = listing.category
    comments = listing.comments.all()
    close_auction = False
    not_signed_in = False

    if request.user == listing.user:
        close_auction = True

    if request.user not in User.objects.all():
        watchlist = ''
        not_signed_in = True
    else: 
        watchlist_item = request.user.watchlist.filter(listing=listing)

        
        if not watchlist_item:
            watchlist = 'Add To Watchlist'
        else:
            watchlist = 'Remove From Watchlist'

    if request.method == 'POST':
        form = NewBidForm(request.POST)
        if request.user not in User.objects.all():
            return render(request, "auctions/listing.html", {
                "listing": listing,
                "form": NewBidForm(),
                "listing_user": listing_user, 
                "bids": bids_no,
                "category": category,
                "bidding_user": request.user, 
                "message": "You must be signed in to bid on a listing",
                "watchlist": watchlist,
                "comment_form": comment_form,
                "comments": comments,
                "close_auction": close_auction,
                "not_signed_in": not_signed_in
            })

        if form.is_valid():
            amount = form.cleaned_data['amount']
            listing = Listing.objects.get(pk=id)

            if amount <= listing.current_bid and bids_no > 0:
               
                return render(request, "auctions/listing.html", {
                    "listing": listing,
                    "form": NewBidForm(),
                    "listing_user": listing_user, 
                    "bids": bids_no,
                    "category": category,
                    "bidding_user": request.user, 
                    "message": "Your bid must be higher than the current bid",
                    "watchlist": watchlist,
                    "comment_form": comment_form,
                    "comments": comments,
                    "close_auction": close_auction,
                    "not_signed_in": not_signed_in
                })
            
            elif amount < listing.current_bid:
                
                return render(request, "auctions/listing.html", {
                    "listing": listing,
                    "form": NewBidForm(),
                    "listing_user": listing_user, 
                    "bids": bids_no,
                    "category": category,
                    "bidding_user": request.user, 
                    "message": "Your bid must be higher than the original price",
                    "watchlist": watchlist,
                    "comment_form": comment_form,
                    "comments": comments,
                    "close_auction": close_auction,
                    "not_signed_in": not_signed_in
                })

            listing.current_bid = amount
            listing.save()
            user = request.user
            
            new_bid = Bid(amount=amount,
                            user=user,
                            listing=listing)
            new_bid.save()
            bids_no = listing.bids.count()

            if bids_no > 0:
                bidding_user = listing.bids.latest('amount').user
                if bidding_user == request.user:
                    bidding_user = "You have the highest bid"
            else:
                bidding_user = "No bidder yet"

            return render(request, "auctions/listing.html", {
                    "listing": listing,
                    "form": NewBidForm(),
                    "listing_user": listing_user, 
                    "bids": bids_no,
                    "category": category,
                    "bidding_user": bidding_user,
                    "watchlist": watchlist,
                    "comment_form": comment_form,
                    "comments": comments,
                    "close_auction": close_auction,
                    "not_signed_in": not_signed_in
                })

    if bids_no > 0:
        bidding_user = listing.bids.latest('amount').user
        if bidding_user == request.user:
                bidding_user = "You have the highest bid"
    else:
        bidding_user = "No bidder yet"
    
    return render(request, "auctions/listing.html", {
        "listing": listing,
        "form": NewBidForm(),
        "listing_user": listing_user, 
        "bids": bids_no,
        "category": category,
        "bidding_user": bidding_user,
        "watchlist": watchlist,
        "comment_form": comment_form,
        "comments": comments,
        "close_auction": close_auction,
        "not_signed_in": not_signed_in
    })

class NewBidForm(forms.Form):
    amount = forms.IntegerField(min_value=1, widget=forms.TextInput(attrs={'class': "form-control", 'placeholder': "Bid"}))

    def __init__(self, *args, **kwargs):
        super(NewBidForm, self).__init__(*args, **kwargs)
        self.fields['amount'].label = ""

@login_required

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %} 

<h1>Categories</h1>

<ul class="list-group">
    {% for category in categories %} 
        <a class="list-group-item" href="{% url 'commerce:category' category %}">{{ category }}</a>
    {% endfor %} 
</ul>


{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %} 

{% block body %} 

    <h1>{{ category }}</h1>

    <h2>Active Listings</h2>

    {% for listing in listings %}
        <div class="listing-container">
            {% if listing.image != "" %}
                <img class="home-page-image" src="{{ listing.image }}" />
            {% endif %}
            <section class="home-page-listing-info">
                <section>
                    <h3><a href="{% url 'commerce:listing' listing.id %}">{{ listing.title }}</a></h3>
                    <span>Price: ${{ listing.current_bid }}</span>
                </section>
                <span class="created-at">Created At: {{ listing.created_at }}</span>
            </section>
        </div>
        {% empty %} 
            <span>No Active Listings</span>
    {% endfor %}

{% endblock %}

auctions/templates/auctions/closed_listing.html
{% extends 'auctions/layout.html' %} 

{% block body %} 
    <div class="listing-wrapper">
        <h2>Listing: {{ listing.title }}</h2>

        <img class="listing-page-image" src="{{ listing.image }}"/>
        <section>{{ listing.description }}</section>
        <strong class="bid">Sold for ${{ listing.current_bid }} to {{ winning_user }}</strong>
        {% if winner %} 
            <span><strong>Congratulations! You won the auction!</strong></span>
        {% endif %} 
        
{% endblock %} 

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    {% for listing in listings %}
        <div class="listing-container">
            {% if listing.image != "" %}
                <img class="home-page-image" src="{{ listing.image }}" />
            {% endif %}
            <section class="home-page-listing-info">
                <section>
                    <h3><a href="{% url 'commerce:listing' listing.id %}">{{ listing.title }}</a></h3>
                    <span>Price: ${{ listing.current_bid }}</span>
                </section>
                <span class="created-at">Created At: {{ listing.created_at }}</span>
            </section>
        </div>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'commerce:index' %}">Active Listings</a>
            </li>
            
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:new' %}">Create a Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:categories' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'commerce:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <div class="listing-wrapper">
        <section class="flex-section">
            <h2>Listing: {{ listing.title }}</h2>
            {% if not_signed_in == False %}
                <form action="{% url 'commerce:toggle_watchlist' listing.id %}" method="post">
                    {% csrf_token %} 
                    <input class="add-to-watchlist-button" type="submit" value="{{ watchlist }}">
                </form>
                {% if close_auction %} 
                    <form action="{% url 'commerce:close_listing' listing.id %}" method="post">
                        {% csrf_token %} 
                        <input class="close-listing" type="submit" value="End Auction">
                    </form>
                {% endif %} 
            {% endif %} 
        </section>
        
        <img class="listing-page-image" src="{{ listing.image }}"/>
        <section>{{ listing.description }}</section>
        <strong class="bid">${{ listing.current_bid }}</strong>
        {% if message != NULL %} 
            <span class="alert alert-danger">{{ message }}</span>
        {% endif %}  
        <span class="bids-span">{{ bids }} bid(s) so far.</span>
        <span class="bids-span">Current bidder: {{ bidding_user }}</span>
        <form class="bid-form" action="{% url 'commerce:listing' listing.id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-primary button-margin" type="submit" value="Place Bid">
        </form>

        <section class="listing-details-section">
            <h3><strong>Details</strong></h3>
            <ul>
                <li>Listed by: {{ listing_user.username }}</li>
                <li>Category: {{ category }}</li>
            </ul>
        </section>
        <section class="comments-section">
            <h3><strong>Comments</strong></h3>
                {% for comment in comments %}
                    <section class="comment-container">
                        <article>{{ comment.comment }}</article>
                        <span class="comment-author">Posted By: {{ comment.user }} at {{ comment.created_at }}</span>
                    </section>
                {% endfor %} 
                {% if not_signed_in == False %}
                    <form class="form-group" action="{% url 'commerce:add_comment' listing.id %}" method="post">
                        {% csrf_token %}
                        {{ comment_form }}
                        <input type="submit" class="btn btn-primary button-margin" value="Post Comment">
                    </form>
                {% endif %} 
        </section>
    </div>
    

{% endblock %} 

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'commerce:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'commerce:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/new.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="page-wrapper">
    <h1>New Listing</h1>

    <span>{{ message }}</span>

    <form class="form" action="{% url 'commerce:new' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <select name="category" class="form-control">
                <option value="" disabled selected>Select Category</option>
                {% for category in categories %}
                    <option value="{{ category.name }}">{{ category.name }}</option>
                {% endfor %}  
            </select>
        </p>
        <p>
            <input class="btn btn-primary" value="Create Listing" type="submit">
        </p>
    </form>
</div>
 
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'commerce:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'commerce:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %} 

{% block body %}
    <h2>My Watchlist</h2>

    {% for listing in listings %}
        <div class="listing-container">
            {% if listing.image != "" %}
                <img class="home-page-image" src="{{ listing.image }}" />
            {% endif %}
            <section class="home-page-listing-info">
                <section>
                    <h3><a href="{% url 'commerce:listing' listing.id %}">{{ listing.title }}</a></h3>
                    <span>Price: ${{ listing.current_bid }}</span>
                </section>
                <span class="created-at">Created At: {{ listing.created_at }}</span>
            </section>
        </div>
    {% endfor %}
{% endblock %}